name       : opus
version    : 1.1.4
homepage   : https://www.opus-codec.org/
release    : 4
source     :
    - http://downloads.xiph.org/releases/opus/opus-1.1.4.tar.gz : 9122b6b380081dd2665189f97bfd777f04f92dc3ab6698eea1dbb27ad59d8692
license    : BSD
component  : multimedia.codecs
summary    : Opus is a totally open, royalty-free, highly versatile audio codec.
description: |
    Opus is a totally open, royalty-free, highly versatile audio codec.
libsplit   : no
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
