name       : opus
version    : '1.4'
homepage   : https://www.opus-codec.org/
release    : 11
source     :
    - git|https://github.com/xiph/opus.git: v1.4
license    : BSD-3-Clause
component  : multimedia.codecs
summary    : Opus is a totally open, royalty-free, highly versatile audio codec.
description: |
    Opus is a totally open, royalty-free, highly versatile audio codec. Opus is unmatched for interactive speech and music transmission over the Internet, but is also intended for storage and streaming applications. It is standardized by the Internet Engineering Task Force (IETF) as RFC 6716 which incorporated technology from Skype’s SILK codec and Xiph.Org’s CELT codec.
libsplit   : no
emul32     : yes
setup      : |
    %meson_configure -Dcustom-modes=true
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
