name       : opus
version    : 1.3.1
homepage   : https://www.opus-codec.org/
release    : 9
source     :
    - https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz : 65b58e1e25b2a114157014736a3d9dfeaad8d41be1c8179866f144a2fb44ff9d
license    : BSD-3-Clause
component  : multimedia.codecs
summary    : Opus is a totally open, royalty-free, highly versatile audio codec.
description: |
    Opus is a totally open, royalty-free, highly versatile audio codec. Opus is unmatched for interactive speech and music transmission over the Internet, but is also intended for storage and streaming applications. It is standardized by the Internet Engineering Task Force (IETF) as RFC 6716 which incorporated technology from Skype’s SILK codec and Xiph.Org’s CELT codec.
libsplit   : no
setup      : |
    %configure --disable-static --enable-update-draft
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
