name       : opus
version    : 1.1.2
release    : 2
source     :
    - http://downloads.xiph.org/releases/opus/opus-1.1.2.tar.gz : 0e290078e31211baa7b5886bcc8ab6bc048b9fc83882532da4a1a45e58e907fd
license    : BSD
component  : desktop.multimedia
summary    : Opus is a totally open, royalty-free, highly versatile audio codec.
description: |
    Opus is a totally open, royalty-free, highly versatile audio codec.
libsplit : no
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
