name       : opus
version    : 1.1
release    : 1
source     :
    - http://downloads.xiph.org/releases/opus/opus-1.1.tar.gz : b9727015a58affcf3db527322bf8c4d2fcf39f5f6b8f15dbceca20206cbe1d95
license    : BSD
summary    : Opus is a totally open, royalty-free, highly versatile audio codec.
description: |
    Opus is a totally open, royalty-free, highly versatile audio codec.
libsplit : no
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
